### ISSUE TITLE
PMTK commands

### ISSUE THREAD

**Issue by emrelio** [nimaltd/NMEA#3]
Hi! I'm using your library for parsing coordinates. Thank you for that.
But when I try to send PMTK command to the GPS nothing happens.

For example, I'm sending like that;

	char TxBuffer[] = "$PMTK314,0,0,0,1,0,0,0,0,0,0,0,0,0,0*35\r\n";
	HAL_UART_Transmit(&huart1, (uint8_t *)TxBuffer, sizeof(TxBuffer), 100);

there is no response and GPS keeps dumping all the data packages.

When I try the GPS with ftdi232 and RealTerm app, after that I did send this command GPS giving only GPGGA package.

Is there any solution for this problem?

Thank you.

**Comment by nimaltd** [comment]
Most gps module are not configurable.

**Comment by emrelio** [comment]
But my GPS model is L80-M39. And when I try to configure without UC, with USB to UART adapter it works.

**Comment by nimaltd** [comment]
My test module is neo 6 . I dont have any gps module yet

**Comment by emrelio** [comment]
Thanks. I just solved the problem. I was trying to use the module with the stm32f4 discovery board. And the pins that I was trying to use are the same with USB OTG pins.
When I try to use another pin config everything worked.
